/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import ClaseAux.Mensaje;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Jeanca
 */
public class AuxPlantillas extends javax.swing.JFrame {

    /**
     * Creates new form AuxPlantillas
     */
    public AuxPlantillas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        agregar_jugador = new javax.swing.JButton();
        eliminar_jugador = new javax.swing.JButton();
        agregar_capitan = new javax.swing.JButton();
        eliminar_capitan = new javax.swing.JButton();
        agregar_gol = new javax.swing.JButton();
        eliminar_gol = new javax.swing.JButton();
        agregar_cuerpo_tecnico = new javax.swing.JButton();
        eliminar_cuerpo_tecnico = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel1.setText("Agregar o Eliminar Plantilla Local/Visita");

        agregar_jugador.setText("Agregar Jugador");
        agregar_jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_jugadorActionPerformed(evt);
            }
        });

        eliminar_jugador.setText("Eliminar Jugador");
        eliminar_jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_jugadorActionPerformed(evt);
            }
        });

        agregar_capitan.setText("Agrega Capitán");
        agregar_capitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_capitanActionPerformed(evt);
            }
        });

        eliminar_capitan.setText("Eliminar Capitán");
        eliminar_capitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_capitanActionPerformed(evt);
            }
        });

        agregar_gol.setText("Agregar Gol");
        agregar_gol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_golActionPerformed(evt);
            }
        });

        eliminar_gol.setText("Eliminar Gol");
        eliminar_gol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_golActionPerformed(evt);
            }
        });

        agregar_cuerpo_tecnico.setText("Ag. Cuerp. Tec");
        agregar_cuerpo_tecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_cuerpo_tecnicoActionPerformed(evt);
            }
        });

        eliminar_cuerpo_tecnico.setText("Elim. Cuerp. Tec");
        eliminar_cuerpo_tecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_cuerpo_tecnicoActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local", "Visita" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agregar_cuerpo_tecnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agregar_jugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agregar_gol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agregar_capitan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eliminar_jugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminar_capitan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminar_gol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminar_cuerpo_tecnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_jugador)
                    .addComponent(eliminar_jugador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_capitan)
                    .addComponent(eliminar_capitan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_gol)
                    .addComponent(eliminar_gol))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_cuerpo_tecnico)
                    .addComponent(eliminar_cuerpo_tecnico))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // AGREGA UN TITULAR DE EQUIPO LOCAL
    private void agregar_jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_jugadorActionPerformed
        // TODO add your handling code here:
        try {
            JTextField entradaNumPartido = new JTextField();
            JTextField entradaCodigoEquipo = new JTextField();
            JTextField entradaPasaporte = new JTextField();
            Object[] mensaje = { "Número Partido: ", entradaNumPartido,
                "Codigo de Equipo: ", entradaCodigoEquipo,
                "Número de Pasaporte: ", entradaPasaporte };
            int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Llene la siguiente información: ", JOptionPane.OK_CANCEL_OPTION);
            if (opcion == JOptionPane.OK_OPTION) {
                String numPartido = entradaNumPartido.getText();
                String codigoEquipo = entradaCodigoEquipo.getText();
                String numPasaporte = entradaPasaporte.getText();
                if (numPartido.equals("") || codigoEquipo.equals("") || numPasaporte.equals("")) {
                    ClaseAux.Mensaje.entradaVacia();
                } else {
                    String tipo = (String) jComboBox1.getSelectedItem();
                    if (tipo.equals("Local")) {
                        Conexion.Conexion.realizarConsulta("" +
                            "INSERT INTO pantilla_titular_equipo_local VALUES (" +
                            "" + numPartido +
                            ",'" + codigoEquipo +
                            "'," + numPasaporte + ")");
                        ClaseAux.Mensaje.mensajeCrearCRUD();
                    } else {
                        Conexion.Conexion.realizarConsulta("" +
                            "INSERT INTO pantilla_titular_equipo_visita VALUES (" +
                            "" + numPartido +
                            "," + codigoEquipo +
                            ",'" + numPasaporte + "')");
                        ClaseAux.Mensaje.mensajeCrearCRUD();
                    }
                }
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ClaseAux.Mensaje.mensajeError(ex.toString());
        }
    }//GEN-LAST:event_agregar_jugadorActionPerformed

    private void eliminar_jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_jugadorActionPerformed
        // TODO add your handling code here:
        try {
            JTextField entradaPasaporte = new JTextField();
            Object[] mensaje = { "Pasaporte Jugador: ", entradaPasaporte };
            int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Llene la siguiente información: ", JOptionPane.OK_CANCEL_OPTION);
            if (opcion == JOptionPane.OK_OPTION) {
                String pasaporte = entradaPasaporte.getText();
                if (pasaporte.equals("")) {
                    Mensaje.entradaVacia();
                } else {
                    String tipo = (String) jComboBox1.getSelectedItem();
                    if (tipo.equals("Local")) {
                        Conexion.Conexion.realizarConsulta("" +
                            "DELETE FROM pantilla_titular_equipo_local WHERE numero_pasaporte_jugador = " + pasaporte);
                        ClaseAux.Mensaje.mensajeBorrarCRUD();
                    } else {
                        Conexion.Conexion.realizarConsulta("" +
                            "DELETE FROM pantilla_titular_equipo_visita WHERE numero_pasaporte_jugador = " + pasaporte);
                        ClaseAux.Mensaje.mensajeBorrarCRUD();
                    }
                }
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ClaseAux.Mensaje.mensajeError(ex.toString());
        }
    }//GEN-LAST:event_eliminar_jugadorActionPerformed

    private void agregar_capitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_capitanActionPerformed
        // TODO add your handling code here:
        try {
            JTextField entradaNumPartido = new JTextField();
            JTextField entradaCodigoEquipo = new JTextField();
            JTextField entradaPasaporte = new JTextField();
            JTextField entradaInicio = new JTextField();
            JTextField entradaFin = new JTextField();
            Object[] mensaje = { "Número de partido: ", entradaNumPartido,
                "Codigo de Equipo: ", entradaCodigoEquipo,
                "Número de Pasaporte: ", entradaPasaporte,
                "Minuto Inicio: ", entradaInicio,
                "Minuto Fin: ", entradaFin };
            int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Llene la siguiente información: ", JOptionPane.OK_CANCEL_OPTION);
            if (opcion == JOptionPane.OK_OPTION) {
                String numPartido = entradaNumPartido.getText();
                String codigoEquipo = entradaCodigoEquipo.getText();
                String numPasaporte = entradaPasaporte.getText();
                String minInicio = entradaInicio.getText();
                String minFin = entradaFin.getText();
                if (numPartido.equals("") || codigoEquipo.equals("") || numPasaporte.equals("")) {
                    ClaseAux.Mensaje.entradaVacia();
                } else {
                    String tipo = (String) jComboBox1.getSelectedItem();
                    if (tipo.equals("Local")) {
                        Conexion.Conexion.realizarConsulta("" +
                            "INSERT INTO capitan_local VALUES (" +
                            "" + numPartido +
                            ",'" + codigoEquipo +
                            "'," + numPasaporte + 
                            "," + minInicio + 
                            "," + minFin + ")");
                        ClaseAux.Mensaje.mensajeCrearCRUD();
                    } else {
                        Conexion.Conexion.realizarConsulta("" +
                            "INSERT INTO capitan_visita VALUES (" +
                            "" + numPartido +
                            ",'" + codigoEquipo +
                            "'," + numPasaporte + 
                            "," + minInicio + 
                            "," + minFin + ")");
                        ClaseAux.Mensaje.mensajeCrearCRUD();
                    }
                }
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ClaseAux.Mensaje.mensajeError(ex.toString());
        }
    }//GEN-LAST:event_agregar_capitanActionPerformed

    private void eliminar_capitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_capitanActionPerformed
        // TODO add your handling code here:
        try {
            JTextField entradaPasaporte = new JTextField();
            Object[] mensaje = { "Pasaporte Jugador: ", entradaPasaporte };
            int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Llene la siguiente información: ", JOptionPane.OK_CANCEL_OPTION);
            if (opcion == JOptionPane.OK_OPTION) {
                String pasaporte = entradaPasaporte.getText();
                if (pasaporte.equals("")) {
                    Mensaje.entradaVacia();
                } else {
                    String tipo = (String) jComboBox1.getSelectedItem();
                    if (tipo.equals("Local")) {
                        Conexion.Conexion.realizarConsulta("" +
                            "DELETE FROM capitan_local WHERE numero_pasaporte_jugador = " + pasaporte);
                        ClaseAux.Mensaje.mensajeBorrarCRUD();
                    } else {
                        Conexion.Conexion.realizarConsulta("" +
                            "DELETE FROM capitan_visita WHERE numero_pasaporte_jugador = " + pasaporte);
                        ClaseAux.Mensaje.mensajeBorrarCRUD();
                    }
                }
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ClaseAux.Mensaje.mensajeError(ex.toString());
        }
    }//GEN-LAST:event_eliminar_capitanActionPerformed

    private void agregar_golActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_golActionPerformed
        // TODO add your handling code here:
        try {
            JTextField entradaNumPartido = new JTextField();
            JTextField entradaPasaporte = new JTextField();
            JTextField entradaCodigoEquipo = new JTextField();
            JTextField entradaMinGol = new JTextField();
            Object[] mensaje = { "Número de partido: ", entradaNumPartido,
                "Codigo de Equipo: ", entradaCodigoEquipo,
                "Número de Pasaporte: ", entradaPasaporte,
                "Minuto Gol: ", entradaMinGol };
            int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Llene la siguiente información: ", JOptionPane.OK_CANCEL_OPTION);
            if (opcion == JOptionPane.OK_OPTION) {
                String numPartido = entradaNumPartido.getText();
                String codigoEquipo = entradaCodigoEquipo.getText();
                String numPasaporte = entradaPasaporte.getText();
                String minGol = entradaMinGol.getText();
                if (numPartido.equals("") || codigoEquipo.equals("") || numPasaporte.equals("")) {
                    ClaseAux.Mensaje.entradaVacia();
                } else {                    
                    Conexion.Conexion.realizarConsulta("" +
                        "INSERT INTO goles_por_partido VALUES (" +
                        "" + numPartido +
                        "," + numPasaporte +
                        ",'" + codigoEquipo + 
                        "'," + minGol + ")");
                    ClaseAux.Mensaje.mensajeCrearCRUD();
                }
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ClaseAux.Mensaje.mensajeError(ex.toString());
        }
    }//GEN-LAST:event_agregar_golActionPerformed

    private void eliminar_golActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_golActionPerformed
        // TODO add your handling code here:
        try {
            JTextField entradaPasaporte = new JTextField();
            Object[] mensaje = { "Pasaporte Jugador: ", entradaPasaporte };
            int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Llene la siguiente información: ", JOptionPane.OK_CANCEL_OPTION);
            if (opcion == JOptionPane.OK_OPTION) {
                String pasaporte = entradaPasaporte.getText();
                if (pasaporte.equals("")) {
                    Mensaje.entradaVacia();
                } else {
                    Conexion.Conexion.realizarConsulta("" +
                        "DELETE FROM goles_por_partido WHERE numero_pasaporte_jugador = " + pasaporte);
                    ClaseAux.Mensaje.mensajeBorrarCRUD();
                }
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ClaseAux.Mensaje.mensajeError(ex.toString());
        }
    }//GEN-LAST:event_eliminar_golActionPerformed

    private void agregar_cuerpo_tecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_cuerpo_tecnicoActionPerformed
        // TODO add your handling code here:
        try {
            JTextField entradaNumPartido = new JTextField();
            JTextField entradaPasaporteTecnico = new JTextField();
            JTextField entradaPasaporteA1 = new JTextField();
            JTextField entradaPasaporteA2 = new JTextField();
            JTextField entradaPasaporteDelegado = new JTextField();
            Object[] mensaje = { "Número de partido: ", entradaNumPartido,
                "Número de Pasaporte Técnico: ", entradaPasaporteTecnico,
                "Número de Pasaporte Asistente1: ", entradaPasaporteA1,
                "Número de Pasaporte Asistente2: ", entradaPasaporteA2,
                "Número de Pasaporte Delegado: ", entradaPasaporteDelegado };
            int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Llene la siguiente información: ", JOptionPane.OK_CANCEL_OPTION);
            if (opcion == JOptionPane.OK_OPTION) {
                String numPartido = entradaNumPartido.getText();
                String pasaporteTecnico = entradaPasaporteTecnico.getText();
                String pasaporteA1 = entradaPasaporteA1.getText();
                String pasaporteA2 = entradaPasaporteA2.getText();
                String pasaporteDelegado = entradaPasaporteDelegado.getText();
                if (numPartido.equals("") || pasaporteTecnico.equals("") || pasaporteA1.equals("")) {
                    ClaseAux.Mensaje.entradaVacia();
                } else {
                    String tipo = (String) jComboBox1.getSelectedItem();
                    if (tipo.equals("Local")) {
                        Conexion.Conexion.realizarConsulta("" +
                            "INSERT INTO cuerpo_tecnico_equipo_local VALUES (" +
                            "" + numPartido +
                            "," + pasaporteTecnico +
                            "," + pasaporteA1 + 
                            "," + pasaporteA2 + 
                            "," + pasaporteDelegado + ")");
                        ClaseAux.Mensaje.mensajeCrearCRUD();
                    } else {
                        Conexion.Conexion.realizarConsulta("" +
                            "INSERT INTO cuerpo_tecnico_equipo_visita VALUES (" +
                            "" + numPartido +
                            "'" + pasaporteTecnico +
                            "," + pasaporteA1 + 
                            "," + pasaporteA2 + 
                            "," + pasaporteDelegado + ")");
                        ClaseAux.Mensaje.mensajeCrearCRUD();
                    }
                }
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ClaseAux.Mensaje.mensajeError(ex.toString());
        }
    }//GEN-LAST:event_agregar_cuerpo_tecnicoActionPerformed

    private void eliminar_cuerpo_tecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_cuerpo_tecnicoActionPerformed
        // TODO add your handling code here:
        try {
            JTextField entradaNumPartido = new JTextField();
            Object[] mensaje = { "Número Partido: ", entradaNumPartido };
            int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Llene la siguiente información: ", JOptionPane.OK_CANCEL_OPTION);
            if (opcion == JOptionPane.OK_OPTION) {
                String numPartido = entradaNumPartido.getText();
                if (numPartido.equals("")) {
                    Mensaje.entradaVacia();
                } else {
                    String tipo = (String) jComboBox1.getSelectedItem();
                    if (tipo.equals("Local")) {
                        Conexion.Conexion.realizarConsulta("" +
                            "DELETE FROM cuerpo_tecnico_equipo_local WHERE numero_partido = " + numPartido);
                        ClaseAux.Mensaje.mensajeBorrarCRUD();
                    } else {
                        Conexion.Conexion.realizarConsulta("" +
                            "DELETE FROM cuerpo_tecnico_equipo_visita WHERE numero_partido = " + numPartido);
                        ClaseAux.Mensaje.mensajeBorrarCRUD();
                    }
                }
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ClaseAux.Mensaje.mensajeError(ex.toString());
        }
    }//GEN-LAST:event_eliminar_cuerpo_tecnicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuxPlantillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuxPlantillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuxPlantillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuxPlantillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuxPlantillas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_capitan;
    private javax.swing.JButton agregar_cuerpo_tecnico;
    private javax.swing.JButton agregar_gol;
    private javax.swing.JButton agregar_jugador;
    private javax.swing.JButton eliminar_capitan;
    private javax.swing.JButton eliminar_cuerpo_tecnico;
    private javax.swing.JButton eliminar_gol;
    private javax.swing.JButton eliminar_jugador;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
