/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author Jeanca
 */
public class Principal extends javax.swing.JFrame {
    
    private Diccionario diccionario;
    private AcercaDe acercaDe;
    private CRUDEquipo crudEquipo;
    private CRUDPartido crudPartido;
    private final ImageIcon iconoFlecha = new ImageIcon(getClass().getResource("/Complementos/flecha.png"));
    private final ImageIcon iconoMundial = new ImageIcon(getClass().getResource("/Complementos/icono_rusia.png"));
    
    /**
     * Creates new form Principal
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public Principal() {
        initComponents();
        this.jLabel1.setText(""); this.jLabel1.setIcon(iconoFlecha);
        this.jLabel2.setText(""); this.jLabel2.setIcon(iconoFlecha);
        this.jLabel3.setText(""); this.jLabel3.setIcon(iconoFlecha);
        this.jLabel4.setText(""); this.jLabel4.setIcon(iconoFlecha);
        this.jLabel5.setText(""); this.jLabel5.setIcon(iconoFlecha);
        this.jLabel6.setText(""); this.jLabel6.setIcon(iconoFlecha);
        this.jLabel7.setText(""); this.jLabel7.setIcon(iconoFlecha);
        this.imagen_jLabel.setIcon(iconoMundial);
        this.imagen_jPanel.setBackground(new java.awt.Color(25, 30, 39));
        
        this.menu_principal_jLabel.setForeground(Color.WHITE);
        this.ver_participantes_por_confederaciones_jLabel.setForeground(Color.WHITE);
        ClaseAux.LabelListener.LabelListener(this.ver_participantes_por_confederaciones_jLabel, 1);
        this.ver_confederaciones_con_equipos_jLabel.setForeground(Color.WHITE);
        ClaseAux.LabelListener.LabelListener(this.ver_confederaciones_con_equipos_jLabel, 2);
        this.ver_informe_partidos_jLabel.setForeground(Color.WHITE);
        ClaseAux.LabelListener.LabelListener(this.ver_informe_partidos_jLabel, 3);
        this.ver_grupos_calificaciones_jLabel.setForeground(Color.WHITE);
        ClaseAux.LabelListener.LabelListener(this.ver_grupos_calificaciones_jLabel, 4);
        this.ver_tabla_general_posiciones_jLabel.setForeground(Color.WHITE);
        ClaseAux.LabelListener.LabelListener(this.ver_tabla_general_posiciones_jLabel, 5);
        this.ver_tabla_goleadores_jLabel.setForeground(Color.WHITE);
        ClaseAux.LabelListener.LabelListener(this.ver_tabla_goleadores_jLabel, 6);
        this.ver_estadios_jLabel.setForeground(Color.WHITE);
        ClaseAux.LabelListener.LabelListener(this.ver_estadios_jLabel, 7);
        this.setDefaultCloseOperation(Principal.DO_NOTHING_ON_CLOSE);
        this.setBounds(250, 50, 850, 570);
        this.setTitle("Mundial");
        this.getContentPane().setBackground(new java.awt.Color(25, 30, 39));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_principal_jLabel = new javax.swing.JLabel();
        ver_informe_partidos_jLabel = new javax.swing.JLabel();
        ver_participantes_por_confederaciones_jLabel = new javax.swing.JLabel();
        ver_confederaciones_con_equipos_jLabel = new javax.swing.JLabel();
        ver_grupos_calificaciones_jLabel = new javax.swing.JLabel();
        ver_tabla_general_posiciones_jLabel = new javax.swing.JLabel();
        ver_tabla_goleadores_jLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        imagen_jPanel = new javax.swing.JPanel();
        imagen_jLabel = new javax.swing.JLabel();
        ver_estadios_jLabel = new javax.swing.JLabel();
        principal_jMenuBar = new javax.swing.JMenuBar();
        opciones_jMenu = new javax.swing.JMenu();
        crud_jMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        diccionario_jMenuItem = new javax.swing.JMenuItem();
        ayuda_jMenuItem = new javax.swing.JMenuItem();
        acerca_de_jMenuItem = new javax.swing.JMenuItem();
        salir_jMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_principal_jLabel.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        menu_principal_jLabel.setText("Menú Principal");

        ver_informe_partidos_jLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ver_informe_partidos_jLabel.setText("Ver Informe de Partidos");

        ver_participantes_por_confederaciones_jLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ver_participantes_por_confederaciones_jLabel.setText("Ver Participantes por Confederaciones");

        ver_confederaciones_con_equipos_jLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ver_confederaciones_con_equipos_jLabel.setText("Ver Confederaciones con Equipos");

        ver_grupos_calificaciones_jLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ver_grupos_calificaciones_jLabel.setText("Ver Grupos y Calificaciones");

        ver_tabla_general_posiciones_jLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ver_tabla_general_posiciones_jLabel.setText("Ver Tabla General de Posiciones");

        ver_tabla_goleadores_jLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ver_tabla_goleadores_jLabel.setText("Ver Tabla de Goleadores");

        jLabel1.setText("1");

        jLabel2.setText("2");

        jLabel3.setText("3");

        jLabel4.setText("4");

        jLabel5.setText("5");

        jLabel6.setText("6");

        jLabel7.setText("7");

        javax.swing.GroupLayout imagen_jPanelLayout = new javax.swing.GroupLayout(imagen_jPanel);
        imagen_jPanel.setLayout(imagen_jPanelLayout);
        imagen_jPanelLayout.setHorizontalGroup(
            imagen_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagen_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen_jLabel)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        imagen_jPanelLayout.setVerticalGroup(
            imagen_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagen_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen_jLabel)
                .addContainerGap(364, Short.MAX_VALUE))
        );

        ver_estadios_jLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ver_estadios_jLabel.setText("Ver Estadios");

        opciones_jMenu.setForeground(new java.awt.Color(0, 0, 0));
        opciones_jMenu.setText("Opciones");

        crud_jMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/balon_futbol.png"))); // NOI18N
        crud_jMenuItem.setText("CRUD Equipos");
        crud_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crud_jMenuItemActionPerformed(evt);
            }
        });
        opciones_jMenu.add(crud_jMenuItem);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/balon_futbol.png"))); // NOI18N
        jMenuItem1.setText("CRUD Partidos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        opciones_jMenu.add(jMenuItem1);

        diccionario_jMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/balon_futbol.png"))); // NOI18N
        diccionario_jMenuItem.setText("Diccionario");
        diccionario_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diccionario_jMenuItemActionPerformed(evt);
            }
        });
        opciones_jMenu.add(diccionario_jMenuItem);

        ayuda_jMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/balon_futbol.png"))); // NOI18N
        ayuda_jMenuItem.setText("Ayuda");
        ayuda_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayuda_jMenuItemActionPerformed(evt);
            }
        });
        opciones_jMenu.add(ayuda_jMenuItem);

        acerca_de_jMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/balon_futbol.png"))); // NOI18N
        acerca_de_jMenuItem.setText("Acerca de ...");
        acerca_de_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acerca_de_jMenuItemActionPerformed(evt);
            }
        });
        opciones_jMenu.add(acerca_de_jMenuItem);

        salir_jMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/balon_futbol.png"))); // NOI18N
        salir_jMenuItem.setText("Salir");
        salir_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_jMenuItemActionPerformed(evt);
            }
        });
        opciones_jMenu.add(salir_jMenuItem);

        principal_jMenuBar.add(opciones_jMenu);

        setJMenuBar(principal_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(menu_principal_jLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel7))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ver_tabla_general_posiciones_jLabel)
                            .addComponent(ver_tabla_goleadores_jLabel)
                            .addComponent(ver_grupos_calificaciones_jLabel)
                            .addComponent(ver_confederaciones_con_equipos_jLabel)
                            .addComponent(ver_informe_partidos_jLabel)
                            .addComponent(ver_participantes_por_confederaciones_jLabel)
                            .addComponent(ver_estadios_jLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(imagen_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagen_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menu_principal_jLabel)
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ver_participantes_por_confederaciones_jLabel)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ver_confederaciones_con_equipos_jLabel)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ver_informe_partidos_jLabel)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ver_grupos_calificaciones_jLabel)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ver_tabla_general_posiciones_jLabel)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ver_tabla_goleadores_jLabel)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ver_estadios_jLabel)
                            .addComponent(jLabel7))))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Eventos del menú Opciones del Menú Principal. 
     */
    private void diccionario_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diccionario_jMenuItemActionPerformed
        this.diccionario = new Diccionario();
        this.diccionario.setVisible(true);
    }//GEN-LAST:event_diccionario_jMenuItemActionPerformed

    private void ayuda_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayuda_jMenuItemActionPerformed
        try {
            Desktop.getDesktop().open(new File(ClaseAux.Constantes.PATH_MANUAL));
        } catch (IOException ex) {
            ClaseAux.Mensaje.mensajeError(ex.toString());
        }
    }//GEN-LAST:event_ayuda_jMenuItemActionPerformed

    private void acerca_de_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acerca_de_jMenuItemActionPerformed
        this.acercaDe = new AcercaDe();
        this.acercaDe.setVisible(true);
    }//GEN-LAST:event_acerca_de_jMenuItemActionPerformed

    private void salir_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_jMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salir_jMenuItemActionPerformed

    private void crud_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crud_jMenuItemActionPerformed
        crudEquipo = new CRUDEquipo();
        crudEquipo.setVisible(true);
    }//GEN-LAST:event_crud_jMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        crudPartido = new CRUDPartido();
        crudPartido.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acerca_de_jMenuItem;
    private javax.swing.JMenuItem ayuda_jMenuItem;
    private javax.swing.JMenuItem crud_jMenuItem;
    private javax.swing.JMenuItem diccionario_jMenuItem;
    private javax.swing.JLabel imagen_jLabel;
    private javax.swing.JPanel imagen_jPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel menu_principal_jLabel;
    private javax.swing.JMenu opciones_jMenu;
    private javax.swing.JMenuBar principal_jMenuBar;
    private javax.swing.JMenuItem salir_jMenuItem;
    private javax.swing.JLabel ver_confederaciones_con_equipos_jLabel;
    private javax.swing.JLabel ver_estadios_jLabel;
    private javax.swing.JLabel ver_grupos_calificaciones_jLabel;
    private javax.swing.JLabel ver_informe_partidos_jLabel;
    private javax.swing.JLabel ver_participantes_por_confederaciones_jLabel;
    private javax.swing.JLabel ver_tabla_general_posiciones_jLabel;
    private javax.swing.JLabel ver_tabla_goleadores_jLabel;
    // End of variables declaration//GEN-END:variables
}
