drop table confederacion
drop table equipo
drop table jugador
drop table entrenador
drop table asistente
drop table federativo
drop table arbitro
drop table sede
drop table partido
drop table arbitros_por_partido
drop table capitan_local
drop table cuerpo_tecnico_equipo_local
drop table pantilla_titular_equipo_local
drop table cambios_equipo_local
drop table capitan_visita
drop table cuerpo_tecnico_equipo_visita
drop table pantilla_titular_equipo_visita
drop table cambios_equipo_visita
drop table goles_por_partido
drop table tarjetas_por_partido
drop table penales_por_partido